### ISSUE TITLE
Dark items just show blank on download links 

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-archive#107]
e.g. https://dweb.me/archive/archive.html?item=I_am_too_sexy&download=1&verbose=true
Shows nothing - no errors in console. 

Repeatable on http://localhost:4244/archive/archive.html?item=I_am_too_sexy&download=1&transport=HTTP&mirror=localhost:4244

**Comment by mitra42** [comment]
Fails on server: 
```
  dweb-transports:httptools Fetch of fetching https://dweb.archive.org/metadata/I_am_too_sexy succeeded +1s
  dweb-transports Fetching https://dweb.archive.org/metadata/I_am_too_sexy via HTTP succeeded NaN bytes +1s
  dweb-archivecontroller:ArchiveItem metadata for undefined fetched successfully  +1s
  dweb-transports Uncaught error in fetch TypeError: Cannot read property 'mediatype' of undefined
  dweb-transports     at DwebTransports.fetch (/Users/mitra/git/dweb-mirror/node_modules/@internetarchive/dweb-archivecontroller/ArchiveItem.js:208:82)
  dweb-transports     at prom.then (/Users/mitra/git/dweb-mirror/node_modules/@internetarchive/dweb-transports/Transports.js:227:44)
  dweb-transports     at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
  dweb-transports:httptools p_httpfetch: https://dweb.me/info '' +11s
```

**Comment by mitra42** [comment]
Repeatable at http://localhost:4244/arc/archive.org/metadata/I_am_too_sexy

**Comment by mitra42** [comment]
Correctly shows item is dark now.
